---
# tasks file for update_server

# Update repositories
- name: Update repos
  apt:
    update_cache: yes

# Check the list of packages to update
- name: Check packages to update
  shell:
    cmd: apt list --upgradable | grep -v "En train de lister"
  ignore_errors: yes
  register: packages_update

# Print the list of packages to update
- name: List packages to update
  debug:
    msg: "{{packages_update.stdout_lines}}"
  when: packages_update.stdout_lines

# Update packages
- name: Update
  apt:
    upgrade: full
    autoremove: yes

# Reboot server
- name: Reboot
  reboot:
    test_command: whoami 
