---
# tasks file for update_server

# Update the repositories with "apt" (apt update)
- name : Update repos
  apt:
    update_cache: yes

# Print the list of package(s) marked for update via "apt" (apt list --upgradable)
- name: List packages
  shell:
    cmd: apt list --upgradable
  register: apt_packages_out

- name: List packages out
  debug:
    msg: "{{apt_packages_out.stdout_lines}}"

# Update the server via "apt" (apt full-upgrade && apt autoremove)
- name: Update
  apt:
    upgrade: full
    autoremove: yes

# Reboot to apply changes 
- name: Reboot
  reboot:
    test_command: whoami

