---
# tasks file for add_package

# Stop the playbook if the "package" variable is empty or undefined
- name: Fail if the "package" variable is empty or undefined
  fail:
    msg: The 'package' variable is empty
  when: not package

# Install package(s)
- name: Install package(s)
  apt:
    update_cache: yes
    name: "{{package}}"
    state: present
