---
# tasks file for clean_gitlab_runner

# Clean orphaned docker volumes and unused docker resources on gitlab-runners
- name: Clean unused docker resources
  shell:
    cmd: docker system prune --volumes -af
  register: docker_clean

# Print the output of the clean (to see what have been deleted)
- name: Clean output
  debug:
    msg: "{{docker_clean.stdout_lines}}"
  when: docker_clean.stdout_lines
