---
# tasks file for renew_ssl_certificate

- name: "Renew self-signed certificate"
  ansible.builtin.shell:
    cmd: openssl x509 -signkey /opt/ssl/home-infra.rc.key -in /opt/ssl/home-infra.rc.csr -req -days 365 -out /opt/ssl/home-infra.rc.crt
  register: renew_certificate
  changed_when: true

- name: "Show output"
  ansible.builtin.debug:
    msg: "{{ renew_certificate.stdout_lines }}"
  when: renew_certificate.stdout_lines | length > 0

- name: "Get certificate modulus"
  ansible.builtin.shell:
    cmd: openssl x509 -modulus -noout -in /opt/ssl/home-infra.rc.crt
  register: certificate_modulus
  changed_when: false

- name: "Show certificate modulus"
  ansible.builtin.debug:
    msg: "{{ certificate_modulus.stdout_lines }}"
  when: certificate_modulus.stdout_lines | length > 0

- name: "Get certificate expiration date"
  ansible.builtin.shell:
    cmd: openssl x509 -enddate -noout -in /opt/ssl/home-infra.rc.crt
  register: certificate_exp
  changed_when: false

- name: "Show certificate expiration date output"
  ansible.builtin.debug:
    msg: "{{ certificate_exp.stdout_lines }}"
  when: certificate_exp.stdout_lines | length > 0
