---
# tasks file for update_docker_container

# Pull the latest watchtower image (https://github.com/containrrr/watchtower)
- name: Pull watchtower
  shell:
    cmd: docker pull containrrr/watchtower
  register: pull_watchtower

# Print the output of the pull (to see if there was an update of the image)
- name: Pull watchtower output
  debug:
    msg: "{{pull_watchtower.stdout_lines}}"
  when: pull_watchtower.stdout_lines

# Update every docker containers (if they can be updated) via watchtower
- name: Update docker containers
  shell:
    cmd: docker run --rm -v /var/run/docker.sock:/var/run/docker.sock containrrr/watchtower --porcelain v1 --cleanup --run-once
  register: update_watchtower

# Print the output of the update (to see what services have been updated)
- name: Update docker containers output
  debug:
    msg: "{{update_watchtower.stdout_lines}}" 
  when: update_watchtower.stdout_lines 
