---
# tasks file for update_server

# Update repositories on Debian servers
- name: Update repos - Debian
  ansible.builtin.apt:
    update_cache: true
  when: ansible_facts['distribution'] == "Debian"

# Update repositories on Arch servers
- name: Update repos - Arch
  community.general.pacman:
    update_cache: true
  when: ansible_facts['distribution'] == "Archlinux"

# Update repositories on Arch servers
- name: Update repos - Alpine
  community.general.apk:
    update_cache: true
  when: ansible_facts['distribution'] == "Alpine"

# Check the list of packages to update on Debian servers
- name: Check packages to update - Debian
  ansible.builtin.shell:
    cmd: apt list --upgradable
  register: debian_packages_update
  changed_when: debian_packages_update.rc == 0
  when: ansible_facts['distribution'] == "Debian"

# Check the list of packages to update on Arch servers (requires the "pacman-contrib" package)
- name: Check packages to update - Arch
  ansible.builtin.shell:
    cmd: checkupdates
  ignore_errors: true
  register: arch_packages_update
  changed_when: arch_packages_update.rc == 0
  when: ansible_facts['distribution'] == "Archlinux"

# Check the list of packages to update on Alpine servers
- name: Check packages to update - Alpine
  ansible.builtin.shell:
    cmd: apk list --upgradable
  register: alpine_packages_update
  changed_when: alpine_packages_update.rc == 0
  when: ansible_facts['distribution'] == "Alpine"

# Print the list of packages to update on Debian servers
- name: List packages to update - Debian
  ansible.builtin.debug:
    msg: "{{ debian_packages_update.stdout_lines }}"
  when: ansible_facts['distribution'] == "Debian" and debian_packages_update.stdout_lines

# Print the list of packages to update on Arch servers
- name: List packages to update - Arch
  ansible.builtin.debug:
    msg: "{{ arch_packages_update.stdout_lines }}"
  when: ansible_facts['distribution'] == "Archlinux" and arch_packages_update.stdout_lines

# Print the list of packages to update on Alpine servers
- name: List packages to update - Alpine
  ansible.builtin.debug:
    msg: "{{ alpine_packages_update.stdout_lines }}"
  when: ansible_facts['distribution'] == "Alpine" and alpine_packages_update.stdout_lines

# Update packages on Debian servers
- name: Update - Debian
  ansible.builtin.apt:
    upgrade: full
    autoremove: true
  when: ansible_facts['distribution'] == "Debian"

# Update packages on Arch servers
- name: Update - Arch
  community.general.pacman:
    upgrade: true
  when: ansible_facts['distribution'] == "Archlinux"

# Update packages on Alpine servers
- name: Update - Alpine
  community.general.apk:
    upgrade: true
  when: ansible_facts['distribution'] == "Alpine"

# Check for orphan packages on Arch server
- name: Check orphan packages - Arch
  ansible.builtin.shell:
    cmd: pacman -Qtdq
  ignore_errors: true
  register: arch_orphan_packages
  changed_when: arch_orphan_packages.rc == 0
  when: ansible_facts['distribution'] == "Archlinux"

# Check for orphan packages on Alpine server
- name: Check orphan packages - Alpine
  ansible.builtin.shell:
    cmd: apk list --orphaned
  register: alpine_orphan_packages
  changed_when: alpine_orphan_packages.rc == 0
  when: ansible_facts['distribution'] == "Alpine"

# Print the list of orphan packages (if there are) on Arch servers
- name: List orphan packages - Arch
  ansible.builtin.debug:
    msg: "{{ arch_orphan_packages.stdout_lines }}"
  when: ansible_facts['distribution'] == "Archlinux" and arch_orphan_packages.stdout_lines

# Print the list of orphan packages (if there are) on Alpine servers
- name: List orphan packages - Alpine
  ansible.builtin.debug:
    msg: "{{ alpine_orphan_packages.stdout_lines }}"
  when: ansible_facts['distribution'] == "Alpine" and alpine_orphan_packages.stdout_lines

# Check for pacnew files on Arch servers (requires the "pacman-contrib" package)
- name: Check pacnew files - Arch
  ansible.builtin.shell:
    cmd: pacdiff -o
  register: arch_pacnew_files
  changed_when: arch_pacnew_files.rc == 0
  when: ansible_facts['distribution'] == "Archlinux"

# Check for apk-new files on Alpine servers
- name: Check apk-new files - Alpine
  ansible.builtin.shell:
    cmd: update-conf -a -l
  register: alpine_apk_new_files
  changed_when: alpine_apk_new_files.rc == 0
  when: ansible_facts['distribution'] == "Alpine"

# Print the list of pacnew files (if there are) on Arch servers
- name: List pacnew files - Arch
  ansible.builtin.debug:
    msg: "{{ arch_pacnew_files.stdout_lines }}"
  when: ansible_facts['distribution'] == "Archlinux" and arch_pacnew_files.stdout_lines

# Print the list of apk-new files (if there are) on Alpine servers
- name: List apk-new files - Alpine
  ansible.builtin.debug:
    msg: "{{ alpine_apk_new_files.stdout_lines }}"
  when: ansible_facts['distribution'] == "Alpine" and alpine_apk_new_files.stdout_lines

# Reboot servers (unless it's the Ansible server itself)
- name: Reboot
  ansible.builtin.reboot:
    test_command: whoami
  when: ansible_connection != "local"
