---
- name: "Reboot Bare Metal and VM Servers"
  ansible.builtin.reboot:
  when: ansible_connection != "local" and ansible_facts['virtualization_type'] != "lxc"

- name: "Restart LXC containers"
  community.general.lxc_container:
    name: "{{ inventory_hostname }}"
    state: restarted
  become: false
  when: ansible_connection != "local" and item.group in group_names"
  delegate_to: "{{ item.delegate }}"
  loop:
    - { group: "lxc_core01", delegate: "core01.rc" }
    - { group: "lxc_core02", delegate: "core02.rc" }
