---
# tasks file for delete_user

# Stop the playbook if the "username" var is empty or undefined
- name: Fail if the "username" variable is empty or undefined
  ansible.builtin.fail:
    msg: The 'username' variable is empty
  when: username is undefined or username | length == 0

# Delete the user and its home directory
- name: Delete user
  ansible.builtin.user:
    name: "{{ username }}"
    state: absent
    remove: true
