---
# tasks file for add_package

# Stop the playbook if both the "package_debian" and the "package_arch" variables are empty or undefined
- name: Fail if the "package_debian" and the "package_arch" variables are empty or undefined
  ansible.builtin.fail:
    msg: The 'package_debian' and the 'package_arch' variables are both empty
  when: not package_debian and not package_arch

# Install package(s) on Debian servers
- name: Install package(s) - Debian
  ansible.builtin.apt:
    update_cache: true
    name: "{{ package_debian }}"
    state: present
  when: ansible_facts['distribution'] == "Debian" and package_debian

# Install package(s) on Arch servers
- name: Install package(s) - Arch
  community.general.pacman:
    update_cache: true
    name: "{{ package_arch }}"
    state: present
  when: ansible_facts['distribution'] == "Archlinux" and package_arch

#Hello adn Goodbye
