---
# tasks file for bash_command

# Stop the playbook if the "cmd_debian", the "cmd_arch" and the "cmd_alpine" variables are all empty or undefined
- name: Fail if the "cmd_debian", the "cmd_arch" and the "cmd_alpine" variables are all empty or undefined
  ansible.builtin.fail:
    msg: The 'cmd_debian', the 'cmd_arch' and the 'cmd_alpine' variables are all empty
  when: not cmd_debian and not cmd_arch and not cmd_alpine

# Run the specified bash command on Debian servers
- name: Run bash command - Debian
  ansible.builtin.shell:
    cmd: "{{ cmd_debian }}"
  register: run_cmd_debian
  changed_when: run_cmd_debian.rc == 0
  when: ansible_facts['distribution'] == "Debian" and cmd_debian

# Run the specified bash command on Arch servers
- name: Run bash command - Arch
  ansible.builtin.shell:
    cmd: "{{ cmd_arch }}"
  register: run_cmd_arch
  changed_when: true
  when: ansible_facts['distribution'] == "Archlinux" and cmd_arch

# Run the specified bash command on Alpine servers
- name: Run bash command - Alpine
  ansible.builtin.shell:
    cmd: "{{ cmd_alpine }}"
  register: run_cmd_alpine
  changed_when: run_cmd_alpine.rc == 0
  when: ansible_facts['distribution'] == "Alpine" and cmd_alpine

# Print the standard output of the command (if there is one) for Debian servers
- name: Bash command standard output - Debian
  ansible.builtin.debug:
    msg: "{{ run_cmd_debian.stdout_lines }}"
  when: ansible_facts['distribution'] == "Debian" and run_cmd_debian.stdout_lines

# Print the standard output of the command (if there is one) for Arch servers
- name: Bash command standard output - Arch
  ansible.builtin.debug:
    msg: "{{ run_cmd_arch.stdout_lines }}"
  when: ansible_facts['distribution'] == "Archlinux" and run_cmd_arch.stdout_lines

# Print the standard output of the command (if there is one) for Alpine servers
- name: Bash command standard output - Alpine
  ansible.builtin.debug:
    msg: "{{ run_cmd_alpine.stdout_lines }}"
  when: ansible_facts['distribution'] == "Alpine" and run_cmd_alpine.stdout_lines

# Print the error output of the command (if there is one) for Debian servers
- name: Bash command error output - Debian
  ansible.builtin.debug:
    msg: "{{ run_cmd_debian.stderr_lines }}"
  when: ansible_facts['distribution'] == "Debian" and run_cmd_debian.stderr_lines

# Print the error output of the command (if there is one) for Arch servers
- name: Bash command error output - Arch
  ansible.builtin.debug:
    msg: "{{ run_cmd_arch.stderr_lines }}"
  when: ansible_facts['distribution'] == "Archlinux" and run_cmd_arch.stderr_lines

# Print the error output of the command (if there is one) for Alpine servers
- name: Bash command error output - Alpine
  ansible.builtin.debug:
    msg: "{{ run_cmd_alpine.stderr_lines }}"
  when: ansible_facts['distribution'] == "Alpine" and run_cmd_alpine.stderr_lines
