---
# tasks file for bash_command

# Stop the playbook if the "bash_cmd" variable is empty or undefined
- name: Fail if the "bash_cmd" variable is empty or undefined
  ansible.builtin.fail:
    msg: The 'bash_cmd' variable is empty
  when: not bash_cmd

# Run the specified bash command
- name: Run bash command
  ansible.builtin.shell:
    cmd: "{{ bash_cmd }}"
  register: run_bash_cmd
  changed_when: run_bash_cmd.rc == 0

# Print the standard output of the command (if there is one)
- name: Bash command standard output
  ansible.builtin.debug:
    msg: "{{ run_bash_cmd.stdout_lines }}"
  when: run_bash_cmd.stdout_lines

# Print the error output of the command (if there is one)
- name: Bash command error output
  ansible.builtin.debug:
    msg: "{{ run_bash_cmd.stderr_lines }}"
  when: run_bash_cmd.stderr_lines
