---
# tasks file for update_server

- name: "Update server - Debian"
  ansible.builtin.include_tasks: debian.yml
  when: ansible_facts['distribution'] == "Debian"

- name: "Update server - Arch"
  ansible.builtin.include_tasks: arch.yml
  when: ansible_facts['distribution'] == "Archlinux"

- name: "Update server - Alpine"
  ansible.builtin.include_tasks: alpine.yml
  when: ansible_facts['distribution'] == "Alpine"

- name: Reboot
  ansible.builtin.reboot:
    test_command: whoami
  when: ansible_connection != "local"
