---
# tasks file for update_server

# Update repositories on Debian servers
- name: Update repos - Debian
  apt:
    update_cache: yes
  when: ansible_facts['distribution'] == "Debian"

# Update repositories on Arch servers
- name: Update repos - Arch
  pacman:
    update_cache: yes
  when: ansible_facts['distribution'] == "Archlinux"

# Check the list of packages to update on Debian servers
- name: Check packages to update - Debian
  shell:
    cmd: apt list --upgradable | grep -v "En train de lister"
  ignore_errors: yes
  register: debian_packages_update
  when: ansible_facts['distribution'] == "Debian"

# Check the list of packages to update on Arch servers (requires the "pacman-contrib" package)
- name: Check packages to update - Arch
  shell:
    cmd: checkupdates
  ignore_errors: yes
  register: arch_packages_update
  when: ansible_facts['distribution'] == "Archlinux"

# Print the list of packages to update on Debian servers
- name: List packages to update - Debian
  debug:
    msg: "{{debian_packages_update.stdout_lines}}"
  when: ansible_facts['distribution'] == "Debian" and debian_packages_update.stdout_lines

# Print the list of packages to update on Arch servers
- name: List packages to update - Arch
  debug:
    msg: "{{arch_packages_update.stdout_lines}}"
  when: ansible_facts['distribution'] == "Archlinux" and arch_packages_update.stdout_lines

# Update packages on Debian servers
- name: Update - Debian
  apt:
    upgrade: full
    autoremove: yes
  when: ansible_facts['distribution'] == "Debian"

# Update the Arch Linux keyring (if necessary) on Arch servers
- name: Check archlinux-keyring - Arch
  pacman:
    name: archlinux-keyring
    state: latest
  when: ansible_facts['distribution'] == "Archlinux"

# Update packages on Arch servers
- name: Update - Arch
  pacman:
    upgrade: yes
  when: ansible_facts['distribution'] == "Archlinux"

# Check for pacnew files on Arch servers
- name: Check pacnew files - Arch
  shell:
    cmd: find /etc -regextype posix-extended -regex ".+\.pac(new|save)"
  register: arch_pacnew_files
  when: ansible_facts['distribution'] == "Archlinux"

# Print the list of pacnew files (if there are) on Arch servers
- name: List pacnew files - Arch
  debug:
    msg: "{{arch_pacnew_files.stdout_lines}}"
  when: ansible_facts['distribution'] == "Archlinux" and arch_pacnew_files.stdout_lines

# Reboot servers on the LAN network (see "net" variable in the inventory files)
- name: Reboot - LAN
  reboot:
    test_command: whoami 
  when: net == "LAN" 

# Reboot servers on the DMZ network (see "net" variable in the inventory files)
- name: Reboot - DMZ
  reboot:
    test_command: whoami 
  when: net == "DMZ" 

# Reboot servers on the SERVICE network (see "net" variable in the inventory files), unless it's the Ansible server itself
- name: Reboot - SERVICE
  reboot:
    test_command: whoami 
  when: net == "SERVICE" and ansible_facts['hostname'] != "amprd01"
