---
# tasks file for dump_databases

- name: "Dump the Zabbix database"
  ansible.builtin.shell:
    cmd: docker exec -t postgres-zabbix pg_dumpall -c -U $(cat /opt/postgres/zabbix/env/user) -l $(cat /opt/postgres/zabbix/env/database) | tee /opt/postgres/zabbix/backup/$(date +%d-%m-%Y).dump
  register: dump_zabbix_database
  changed_when: true

- name: "List old dumps of the Zabbix database"
  ansible.builtin.find:
    paths: /opt/postgres/zabbix/backup
    patterns: '*.dump'
    age: 1w
  register: list_old_dumps_zabbix

- name: "Delete old dumps of the Zabbix database"
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: absent
  loop: "{{ list_old_dumps_zabbix.files }}"
