---
# tasks file for proxmox_system_backup

# Perform a full system backup of my Proxmox servers
- name: Proxmox System Backup
  ansible.builtin.shell:
    cmd: system-backup --create --scheduled
    register: proxmox_system_backup
  changed_when: true

# Print the output of the backup (to check that the backup went correctly)
- name: Proxmox System Backup output
  ansible.builtin.debug:
    msg: "{{ proxmox_system_backup.stdout_lines }}"
  when: proxmox_system_backup.stdout_lines | length > 0
