---
# tasks file for delete_user

# Stop the playbook if the "username" var is empty
- name: Check the "username" variable
  fail:
    msg: The 'username' variable is empty
  when: not username

# List all files that either belong to the user or the user's primary group (and print the output through a debug message)
- name: List files
  shell:
    cmd: for i in $(find / -user "{{username}}" -o -group "{{username}}" -name "*" | grep -v "/home/{{username}}"); do ls -ld $i; done
  register: find_out

- name: List files stdout
  debug:
    msg: "{{find_out.stdout_lines}}"
  when: find_out.stdout
- name: List files stderr
  debug:
    msg: "{{find_out.stderr_lines}}"
  when: find_out.stderr.find(username) != -1

# Delete the user and its home directory
- name: Delete user
  user:
    name: "{{username}}"
    state: absent
    remove: yes
    force: yes
