---
# tasks file for delete_user

# Stop the playbook if the "username" var is empty or undefined
- name: Fail if the "username" variable is empty or undefined
  fail:
    msg: The 'username' variable is empty
  when: not username

# Delete the user and its home directory
- name: Delete user
  user:
    name: "{{username}}"
    state: absent
    remove: yes
