---
# tasks file for dump_db

# Perform a dump of the Zabbix's database
- name: Dump Zabbix database
  shell:
    cmd: docker exec -t postgres-zabbix pg_dumpall -c -U $(cat /opt/postgres/zabbix/env/user) -l $(cat /opt/postgres/zabbix/env/database) | tee /opt/postgres/zabbix/backup/$(date +%d-%m-%Y).dump

# Find dumps that are equal to or older than a week
- name: List old dumps
  find:
    paths: /opt/postgres/zabbix/backup
    patterns: '*.dump'
    age: 1w
  register: list_old_dumps

# Delete dumps that are equal to or older than a week (and print them)
- name: Delete old dumps
  file:
    path: "{{item.path}}"
    state: absent
  with_items: "{{list_old_dumps.files}}"
