---
# tasks file for update_antiz.fr

# Update the antiz.fr website on the dev environment
- name: Update antiz.fr website on Dev
  ansible.builtin.shell:
    cmd: cd /opt/antiz.fr && git fetch origin && git checkout origin/dev -- public
  register: update_antiz_fr_dev
  changed_when: update_antiz_fr_dev.rc == 0
  when: env == "dev"

# Update the antiz.fr website on the prod environment
- name: Update antiz.fr website on Prod
  ansible.builtin.shell:
    cmd: cd /opt/antiz.fr && git fetch origin && git checkout origin/main -- public
  register: update_antiz_fr_prd
  changed_when: update_antiz_fr_prd.rc == 0
  when: env == "prod"
