---
title: Home Dashboard

background:
  image: /images/background.png
  blur: sm
  saturate: 25
  brightness: 25
  opacity: 25

cardBlur: sm

theme: dark

color: slate

layout:
  - Monitoring pmx01:
  - Monitoring pmx02:
  - Services Health:
  - Services:
      style: row
      columns: 4
