[__config__]
oldver = "old.txt"
newver = "new.txt"
keyfile = "keyfile.toml"

# GitHub

[actionlint]
source = "github"
github = "rhysd/actionlint"
prefix = "v"
use_max_tag = true
exclude_regex = ".*(pre|a|alpha|b|beta|r|rc).*"

[android-file-transfer]
source = "github"
github = "whoozle/android-file-transfer-linux"
prefix = "v"
use_max_tag = true
exclude_regex = ".*(pre|a|alpha|b|beta|r|rc).*"

[android-udev]
source = "github"
github = "M0Rf30/android-udev-rules"
prefix = "v"
use_max_tag = true
exclude_regex = ".*(pre|a|alpha|b|beta|r|rc).*"

[ansible-bender]
source = "github"
github = "ansible-community/ansible-bender"
prefix = "v"
use_max_tag = true
exclude_regex = ".*(pre|a|alpha|b|beta|r|rc).*"

[ansible-core]
source = "github"
github = "ansible/ansible"
prefix = "v"
use_max_tag = true
exclude_regex = ".*(pre|a|alpha|b|beta|r|rc).*"

[ansible-language-server]
source = "github"
github= "ansible/ansible-language-server"
prefix = "v"
use_max_tag = true
exclude_regex = ".*(pre|a|alpha|b|beta|r|rc).*"

[ansible-lint]
source = "github"
github = "ansible/ansible-lint"
prefix = "v"
use_max_tag = true
exclude_regex = ".*(pre|a|alpha|b|beta|r|rc).*"

[arch-update]
source = "github"
github = "Antiz96/arch-update"
prefix = "v"
use_max_tag = true
exclude_regex = ".*(pre|a|alpha|b|beta|r|rc).*"

[autorandr]
source = "github"
github = "phillipberndt/autorandr"
prefix = "v"
use_max_tag = true
exclude_regex = ".*(pre|a|alpha|b|beta|r|rc).*"

[bats]
source = "github"
github = "bats-core/bats-core"
prefix = "v"
use_max_tag = true
exclude_regex = ".*(pre|a|alpha|b|beta|r|rc|RC).*"

[bd]
source = "github"
github = "vigneshwaranr/bd"
prefix = "v"
use_max_tag = true
exclude_regex = ".*(pre|a|alpha|b|beta|r|rc).*"

[blahaj]
source = "github"
github = "GeopJr/BLAHAJ"
prefix = "v"
use_max_tag = true
exclude_regex = ".*(pre|a|alpha|b|beta|r|rc).*"

[blueman]
source = "github"
github = "blueman-project/blueman"
prefix = "v"
use_max_tag = true
exclude_regex = ".*(pre|a|alpha|b|beta|r|rc).*"

[certificate-ripper]
source = "github"
github = "Hakky54/certificate-ripper"
prefix = "v"
use_max_tag = true
exclude_regex = ".*(pre|a|alpha|b|beta|r|rc).*"

[check-jsonschema]
source = "github"
github = "python-jsonschema/check-jsonschema"
prefix = "v"
use_max_tag = true
exclude_regex = ".*(pre|a|alpha|b|beta|r|rc).*"

[clipboard]
source = "github"
github = "Slackadays/Clipboard"
prefix = "v"
use_max_tag = true
exclude_regex = ".*(pre|a|alpha|b|beta|r|rc).*"

[codespell]
source = "github"
github = "codespell-project/codespell"
prefix = "v"
use_max_tag = true
exclude_regex = ".*(pre|a|alpha|b|beta|r|rc).*"

[containerd]
source = "github"
github = "containerd/containerd"
prefix = "v"
use_max_tag = true
exclude_regex = ".*(pre|a|alpha|b|beta|r|rc).*"

[curlie]
source = "github"
github = "rs/curlie"
prefix = "v"
use_max_tag = true
exclude_regex = ".*(pre|a|alpha|b|beta|r|rc).*"

[ddgr]
source = "github"
github = "jarun/ddgr"
prefix = "v"
use_max_tag = true
exclude_regex = ".*(pre|a|alpha|b|beta|r|rc).*"

[dino]
source = "github"
github = "dino/dino"
prefix = "v"
use_max_tag = true
exclude_regex = ".*(pre|a|alpha|b|beta|r|rc).*"

[distrobox]
source = "github"
github = "89luca89/distrobox"
prefix = "v"
use_max_tag = true
exclude_regex = ".*(pre|a|alpha|b|beta|r|rc).*"

[dnote]
source = "github"
github = "dnote/dnote"
prefix = "v"
use_latest_tag = true
exclude_regex = ".*(pre|a|alpha|b|beta|r|rc).*"

[elixir]
source = "github"
github = "elixir-lang/elixir"
prefix = "v"
use_max_tag = true
exclude_regex = ".*(pre|a|alpha|b|beta|r|rc).*"

[entr]
source = "github"
github = "eradman/entr"
prefix = "v"
use_max_tag = true
exclude_regex = ".*(pre|a|alpha|b|beta|r|rc).*"

[fastfetch]
source = "github"
github = "fastfetch-cli/fastfetch"
prefix = "v"
use_max_tag = true
exclude_regex = ".*(pre|a|alpha|b|beta|r|rc).*"

[firewalld]
source = "github"
github = "firewalld/firewalld"
prefix = "v"
use_max_tag = true
exclude_regex = ".*(pre|a|alpha|b|beta|r|rc).*"

[font-awesome]
source = "github"
github = "FortAwesome/Font-Awesome"
prefix = "v"
use_max_tag = true
exclude_regex = ".*(pre|a|alpha|b|beta|r|rc).*"

[girara]
source = "github"
github = "pwmt/girara"
prefix = "v"
use_max_tag = true
exclude_regex = ".*(pre|a|alpha|b|beta|r|rc).*"

[gitea]
source = "github"
github = "go-gitea/gitea"
prefix = "v"
use_max_tag = true
exclude_regex = ".*(pre|a|alpha|b|beta|r|rc|dev).*"

[gitmux]
source = "github"
github = "arl/gitmux"
prefix = "v"
use_max_tag = true
exclude_regex = ".*(pre|a|alpha|b|beta|r|rc).*"

[glances]
source = "github"
github = "nicolargo/glances"
prefix = "v"
use_max_tag = true
exclude_regex = ".*(pre|a|alpha|b|beta|r|rc).*"

[glow]
source = "github"
github = "charmbracelet/glow"
prefix = "v"
use_max_tag = true
exclude_regex = ".*(pre|a|alpha|b|beta|r|rc).*"

[goverlay]
source = "github"
github = "benjamimgois/goverlay"
prefix = "v"
use_max_tag = true
exclude_regex = ".*(pre|a|alpha|b|beta|r|rc).*"

[grafana-zabbix]
source = "github"
github = "grafana/grafana-zabbix"
prefix = "v"
use_max_tag = true
exclude_regex = ".*(pre|a|alpha|b|beta|r|rc).*"

[gsimplecal]
source = "github"
github = "dmedvinsky/gsimplecal"
prefix = "v"
use_max_tag = true
exclude_regex = ".*(pre|a|alpha|b|beta|r|rc).*"

[hexchat]
source = "github"
github = "hexchat/hexchat"
prefix = "v"
use_max_tag = true
exclude_regex = ".*(pre|a|alpha|b|beta|r|rc).*"

[htmlq]
source = "github"
github = "mgdm/htmlq"
prefix = "v"
use_max_tag = true
exclude_regex = ".*(pre|a|alpha|b|beta|r|rc).*"

[hugo]
source = "github"
github = "gohugoio/hugo"
prefix = "v"
use_max_tag = true
exclude_regex = ".*(pre|a|alpha|b|beta|r|rc).*"

[hyfetch]
source = "github"
github = "hykilpikonna/hyfetch"
prefix = "v"
use_max_tag = true
exclude_regex = ".*(pre|a|alpha|b|beta|r|rc).*"

[icewm]
source = "github"
github = "ice-wm/icewm"
prefix = "v"
use_max_tag = true
exclude_regex = ".*(pre|a|alpha|b|beta|r|rc).*"

[iotop-c]
source = "github"
github = "Tomas-M/iotop"
prefix = "v"
use_max_tag = true
exclude_regex = ".*(pre|a|alpha|b|beta|r|rc).*"

[jbig2dec]
source = "github"
github = "ArtifexSoftware/jbig2dec"
prefix = "v"
use_max_tag = true
exclude_regex = ".*(pre|a|alpha|b|beta|r|rc).*"

[jenkins]
source = "github"
github = "jenkinsci/jenkins"
prefix = "jenkins-"
use_latest_release = true
exclude_regex = ".*(pre|a|alpha|b|beta|r|rc).*"

[keepassxc]
source = "github"
github = "keepassxreboot/keepassxc"
prefix = "v"
use_max_tag = true
exclude_regex = ".*(pre|a|alpha|b|beta|r|rc).*"

[lemurs]
source = "github"
github = "coastalwhite/lemurs"
prefix = "v"
use_max_tag = true
exclude_regex = ".*(pre|a|alpha|b|beta|r|rc).*"

[libcgif]
source = "github"
github = "dloebl/cgif"
prefix = "V"
use_max_tag = true
exclude_regex = ".*(pre|a|alpha|b|beta|r|rc).*"

[libconfig]
source = "github"
github = "hyperrealm/libconfig"
prefix = "v"
use_max_tag = true
exclude_regex = ".*(pre|a|alpha|b|beta|r|rc).*"

[libu2f-server]
source = "github"
github = "Yubico/libu2f-server"
prefix = "libu2f-server-"
use_latest_tag = true
exclude_regex = ".*(pre|a|alpha|b|beta|r|rc).*"

[limine]
source = "github"
github = "limine-bootloader/limine"
prefix = "v"
use_max_tag = true
exclude_regex = ".*(pre|a|alpha|b|beta|r|rc).*"

[lowcharts]
source = "github"
github = "juan-leon/lowcharts"
prefix = "v"
use_max_tag = true
exclude_regex = ".*(pre|a|alpha|b|beta|r|rc).*"

[lutris]
source = "github"
github = "lutris/lutris"
prefix = "v"
use_max_tag = true
exclude_regex = ".*(pre|a|alpha|b|beta|r|rc).*"

[malias]
source = "github"
github = "Antiz96/malias"
prefix = "v"
use_max_tag = true
exclude_regex = ".*(pre|a|alpha|b|beta|r|rc).*"

[markdownlint]
source = "github"
github = "markdownlint/markdownlint"
prefix = "v"
use_max_tag = true
exclude_regex = ".*(pre|a|alpha|b|beta|r|rc).*"

[molecule]
source = "github"
github = "ansible/molecule"
prefix = "v"
use_max_tag = true
exclude_regex = ".*(pre|a|alpha|b|beta|r|rc).*"

[mpv]
source = "github"
github = "mpv-player/mpv"
prefix = "v"
use_max_tag = true
exclude_regex = ".*(pre|a|alpha|b|beta|r|rc).*"

[mupdf]
source = "github"
github = "ArtifexSoftware/mupdf"
prefix = "v"
use_max_tag = true
exclude_regex = ".*(pre|a|alpha|b|beta|r|rc).*"

[nebula]
source = "github"
github = "slackhq/nebula"
prefix = "v"
use_max_tag = true
exclude_regex = ".*(pre|a|alpha|b|beta|r|rc).*"

[nfoview]
source = "github"
github = "otsaloma/nfoview"
prefix = "v"
use_max_tag = true
exclude_regex = ".*(pre|a|alpha|b|beta|r|rc).*"

[nwg-icon-picker]
source = "github"
github = "nwg-piotr/nwg-icon-picker"
prefix = "v"
use_max_tag = true
exclude_regex = ".*(pre|a|alpha|b|beta|r|rc).*"

[nwg-look]
source = "github"
github = "nwg-piotr/nwg-look"
prefix = "v"
use_max_tag = true
exclude_regex = ".*(pre|a|alpha|b|beta|r|rc).*"

[nwg-panel]
source = "github"
github = "nwg-piotr/nwg-panel"
prefix = "v"
use_max_tag = true
exclude_regex = ".*(pre|a|alpha|b|beta|r|rc).*"

[oculante]
source = "github"
github = "woelper/oculante"
prefix = "v"
use_max_tag = true
exclude_regex = ".*(pre|a|alpha|b|beta|r|rc).*"

[only-office]
source = "github"
github = "ONLYOFFICE/DesktopEditors"
prefix = "v"
use_max_tag = true
exclude_regex = ".*(pre|a|alpha|b|beta|r|rc).*"

[pam_u2f]
source = "github"
github = "Yubico/pam-u2f"
prefix = "pam_u2f-"
use_latest_tag = true
exclude_regex = ".*(pre|a|alpha|b|beta|r|rc).*"

[pasystray]
source = "github"
github = "christophgysin/pasystray"
prefix = "v"
use_max_tag = true
exclude_regex = ".*(pre|a|alpha|b|beta|r|rc).*"

[pdfjs_pdfjs-legacy]
source = "github"
github = "mozilla/pdf.js"
prefix = "v"
use_max_tag = true
exclude_regex = ".*(pre|a|alpha|b|beta|r|rc).*"

[picom]
source = "github"
github = "yshui/picom"
prefix = "v"
use_max_tag = true
exclude_regex = ".*(pre|a|alpha|b|beta|r|rc).*"

[piper]
source = "github"
github = "libratbag/piper"
prefix = "v"
use_max_tag = true
exclude_regex = ".*(pre|a|alpha|b|beta|r|rc).*"

[powerline]
source = "github"
github = "powerline/powerline"
prefix = "v"
use_max_tag = true
exclude_regex = ".*(pre|a|alpha|b|beta|r|rc).*"

[pychess]
source = "github"
github = "pychess/pychess"
prefix = "v"
use_max_tag = true
exclude_regex = ".*(pre|a|alpha|b|beta|r|rc).*"

[python-ansible-compat]
source = "github"
github = "ansible/ansible-compat"
prefix = "v"
use_max_tag = true
exclude_regex = ".*(pre|a|alpha|b|beta|r|rc).*"

[python-dasbus]
source = "github"
github = "dasbus-project/dasbus"
prefix = "v"
use_max_tag = true
exclude_regex = ".*(pre|a|alpha|b|beta|r|rc).*"

[python-fastapi]
source = "github"
github = "tiangolo/fastapi"
prefix = "v"
use_max_tag = true
exclude_regex = ".*(pre|a|alpha|b|beta|r|rc).*"

[python-gnupg]
source = "github"
github = "vsajip/python-gnupg"
prefix = "v"
use_max_tag = true
exclude_regex = ".*(pre|a|alpha|b|beta|r|rc).*"

[python-i3ipc]
source = "github"
github = "altdesktop/i3ipc-python"
prefix = "v"
use_max_tag = true
exclude_regex = ".*(pre|a|alpha|b|beta|r|rc).*"

[python-mistune]
source = "github"
github = "lepture/mistune"
prefix = "v"
use_max_tag = true
exclude_regex = ".*(pre|a|alpha|b|beta|r|rc).*"

[python-precis_i18n]
source = "github"
github = "byllyfish/precis_i18n"
prefix = "v"
use_max_tag = true
exclude_regex = ".*(pre|a|alpha|b|beta|r|rc).*"

[python-pymupdf]
source = "github"
github = "pymupdf/PyMuPDF"
prefix = "v"
use_max_tag = true
exclude_regex = ".*(pre|a|alpha|b|beta|r|rc).*"

[python-sentry_sdk]
source = "github"
github = "getsentry/sentry-python"
prefix = "v"
use_max_tag = true
exclude_regex = ".*(pre|a|alpha|b|beta|r|rc).*"

[python-starlette]
source = "github"
github = "encode/starlette"
prefix = "v"
use_max_tag = true
exclude_regex = ".*(pre|a|alpha|b|beta|r|rc).*"

[python-tabulate]
source = "github"
github = "astanin/python-tabulate"
prefix = "v"
use_max_tag = true
exclude_regex = ".*(pre|a|alpha|b|beta|r|rc).*"

[python-textual]
source = "github"
github = "Textualize/textual"
prefix = "v"
use_max_tag = true
exclude_regex = ".*(pre|a|alpha|b|beta|r|rc).*"

[python-tqdm]
source = "github"
github = "tqdm/tqdm"
prefix = "v"
use_max_tag = true
exclude_regex = ".*(pre|a|alpha|b|beta|r|rc).*"

[python-userpath]
source = "github"
github = "ofek/userpath"
prefix = "v"
use_max_tag = true
exclude_regex = ".*(pre|a|alpha|b|beta|r|rc).*"

[py3status]
source = "github"
github = "ultrabug/py3status"
prefix = "v"
use_max_tag = true
exclude_regex = ".*(pre|a|alpha|b|beta|r|rc).*"

[rebuild-detector]
source = "github"
github = "maximbaz/rebuild-detector"
prefix = "v"
use_max_tag = true
exclude_regex = ".*(pre|a|alpha|b|beta|r|rc).*"

[redshit]
source = "github"
github = "jonls/redshift"
prefix = "v"
use_max_tag = true
exclude_regex = ".*(pre|a|alpha|b|beta|r|rc).*"

[retsnoop]
source = "github"
github = "anakryiko/retsnoop"
prefix = "v"
use_max_tag = true
exclude_regex = ".*(pre|a|alpha|b|beta|r|rc).*"

[rofi]
source = "github"
github = "davatorium/rofi"
prefix = "v"
use_max_tag = true
exclude_regex = ".*(pre|a|alpha|b|beta|r|rc).*"

[rofi-wayland]
source = "github"
github = "lbonn/rofi"
prefix = "v"
use_max_tag = true
exclude_regex = ".*(pre|a|alpha|b|beta|r|rc).*"

[swappy]
source = "github"
github = "jtheoof/swappy"
prefix = "v"
use_max_tag = true
exclude_regex = ".*(pre|a|alpha|b|beta|r|rc).*"

[sway]
source = "github"
github = "swaywm/sway"
prefix = "v"
use_max_tag = true
exclude_regex = ".*(pre|a|alpha|b|beta|r|rc).*"

[swaybg]
source = "github"
github = "swaywm/swaybg"
prefix = "v"
use_max_tag = true
exclude_regex = ".*(pre|a|alpha|b|beta|r|rc).*"

[sway-contrib]
source = "github"
github = "OctopusET/sway-contrib"
prefix = "v"
use_max_tag = true
exclude_regex = ".*(pre|a|alpha|b|beta|r|rc).*"

[swayidle]
source = "github"
github = "swaywm/swayidle"
prefix = "v"
use_max_tag = true
exclude_regex = ".*(pre|a|alpha|b|beta|r|rc).*"

[swayimg]
source = "github"
github = "artemsen/swayimg"
prefix = "v"
use_max_tag = true
exclude_regex = ".*(pre|a|alpha|b|beta|r|rc).*"

[swaylock]
source = "github"
github = "swaywm/swaylock"
prefix = "v"
use_max_tag = true
exclude_regex = ".*(pre|a|alpha|b|beta|r|rc).*"

[swaync]
source = "github"
github = "ErikReider/SwayNotificationCenter"
prefix = "v"
use_max_tag = true
exclude_regex = ".*(pre|a|alpha|b|beta|r|rc).*"

[systray-x]
source = "github"
github = "Ximi1970/systray-x"
prefix = "v"
use_max_tag = true
exclude_regex = ".*(pre|a|alpha|b|beta|r|rc).*"

[timeshift]
source = "github"
github = "linuxmint/timeshift"
prefix = "v"
use_max_tag = true
exclude_regex = ".*(pre|a|alpha|b|beta|r|rc|master).*"

[touchegg]
source = "github"
github = "JoseExposito/touchegg"
prefix = "v"
use_max_tag = true
exclude_regex = ".*(pre|a|alpha|b|beta|r|rc).*"

[urlwatch]
source = "github"
github = "thp/urlwatch"
prefix = "v"
use_max_tag = true
exclude_regex = ".*(pre|a|alpha|b|beta|r|rc).*"

[vim-ansible]
source = "github"
github = "pearofducks/ansible-vim"
prefix = "v"
use_max_tag = true
exclude_regex = ".*(pre|a|alpha|b|beta|r|rc).*"

[wakeonlan]
source = "github"
github = "jpoliv/wakeonlan"
prefix = "v"
use_max_tag = true
exclude_regex = ".*(pre|a|alpha|b|beta|r|rc).*"

[waybar]
source = "github"
github = "Alexays/Waybar"
prefix = "v"
use_max_tag = true
exclude_regex = ".*(pre|a|alpha|b|beta|r|rc).*"

[wpaperd]
source = "github"
github = "danyspin97/wpaperd"
prefix = "v"
use_max_tag = true
exclude_regex = ".*(pre|a|alpha|b|beta|r|rc).*"

[yubico-piv-tool]
source = "github"
github = "Yubico/yubico-piv-tool"
prefix = "yubico-piv-tool-"
use_latest_tag = true
exclude_regex = ".*(pre|a|alpha|b|beta|r|rc).*"

[yubikey-touch-detector]
source = "github"
github = "maximbaz/yubikey-touch-detector"
prefix = "v"
use_max_tag = true
exclude_regex = ".*(pre|a|alpha|b|beta|r|rc).*"

[yyjson]
source = "github"
github = "ibireme/yyjson"
prefix = "v"
use_latest_tag = true
exclude_regex = ".*(pre|a|alpha|b|beta|r|rc).*"

[zabbix]
source = "github"
github = "zabbix/zabbix"
prefix = "v"
use_max_tag = true
exclude_regex = ".*(pre|a|alpha|b|beta|r|rc).*"

[zaman]
source = "github"
github = "Antiz96/zaman"
prefix = "v"
use_max_tag = true
exclude_regex = ".*(pre|a|alpha|b|beta|r|rc).*"

[zathura]
source = "github"
github = "pwmt/zathura"
prefix = "v"
use_max_tag = true
exclude_regex = ".*(pre|a|alpha|b|beta|r|rc).*"

[zathura-cb]
source = "github"
github = "pwmt/zathura-cb"
prefix = "v"
use_max_tag = true
exclude_regex = ".*(pre|a|alpha|b|beta|r|rc).*"

[zathura-djvu]
source = "github"
github = "pwmt/zathura-djvu"
prefix = "v"
use_max_tag = true
exclude_regex = ".*(pre|a|alpha|b|beta|r|rc).*"

[zathura-pdf-mupdf]
source = "github"
github = "pwmt/zathura-pdf-mupdf"
prefix = "v"
use_max_tag = true
exclude_regex = ".*(pre|a|alpha|b|beta|r|rc).*"

[zathura-pdf-poppler]
source = "github"
github = "pwmt/zathura-pdf-poppler"
prefix = "v"
use_max_tag = true
exclude_regex = ".*(pre|a|alpha|b|beta|r|rc).*"

[zathura-ps]
source = "github"
github = "pwmt/zathura-ps"
prefix = "v"
use_max_tag = true
exclude_regex = ".*(pre|a|alpha|b|beta|r|rc).*"

# GitLab

[ame]
source = "gitlab"
gitlab = "crystal-linux/software/amethyst"
prefix = "v"
use_max_tag = true
exclude_regex = ".*(pre|a|alpha|b|beta|r|rc).*"

[gajim]
source = "gitlab"
host = "dev.gajim.org"
gitlab = "gajim/gajim"
prefix = "v"
use_max_tag = true
exclude_regex = ".*(pre|a|alpha|b|beta|r|rc).*"

[irker]
source = "gitlab"
gitlab = "esr/irker"
prefix = "v"
use_max_tag = true
exclude_regex = ".*(pre|a|alpha|b|beta|r|rc).*"

[kea]
source = "gitlab"
host = "gitlab.isc.org"
gitlab = "isc-projects/kea"
prefix = "Kea-"
use_max_tag = true
#exclude_regex = ".*(pre|a|alpha|b|beta|r|rc).*"

[libplacebo]
source = "gitlab"
host = "code.videolan.org"
gitlab = "videolan/libplacebo"
prefix = "v"
use_max_tag = true
exclude_regex = ".*(pre|a|alpha|b|beta|r|rc).*"

[malachite]
source = "gitlab"
gitlab = "crystal-linux/software/malachite"
prefix = "v"
use_max_tag = true
exclude_regex = ".*(pre|a|alpha|b|beta|r|rc).*"

[notification-daemon]
source = "gitlab"
host = "gitlab.gnome.org"
gitlab = "Archive/notification-daemon"
prefix = "v"
use_max_tag = true
exclude_regex = ".*(pre|a|alpha|b|beta|r|rc).*"

[python-nbxmpp]
source = "gitlab"
host = "dev.gajim.org"
gitlab = "gajim/python-nbxmpp"
prefix = "v"
use_max_tag = true
exclude_regex = ".*(pre|a|alpha|b|beta|r|rc).*"

[python-omemo-dr]
source = "gitlab"
host = "dev.gajim.org"
gitlab = "gajim/omemo-dr"
prefix = "v"
use_max_tag = true
exclude_regex = ".*(pre|a|alpha|b|beta|r|rc).*"

[remmina]
source = "gitlab"
gitlab = "Remmina/Remmina"
prefix = "v"
use_max_tag = true
exclude_regex = ".*(pre|a|alpha|b|beta|r|rc).*"

[tint2]
source = "gitlab"
gitlab = "o9000/tint2"
prefix = "v"
use_max_tag = true
exclude_regex = ".*(pre|a|alpha|b|beta|r|rc).*"

[unrar-free]
source = "gitlab"
gitlab = "bgermann/unrar-free"
prefix = "v"
use_max_tag = true
exclude_regex = ".*(pre|a|alpha|b|beta|r|rc).*"

# Pypi

[ansible]
source = "pypi"
pypi = "ansible"
prefix = "v"
exclude_regex = ".*(pre|a|alpha|b|beta|r|rc).*"

[python-zabbix-api]
source = "pypi"
pypi = "zabbix-api"
prefix = "v"
exclude_regex = ".*(pre|a|alpha|b|beta|r|rc).*"

# Git

[bluez]
source = "git"
git = "https://git.kernel.org/pub/scm/bluetooth/bluez.git"
prefix = "v"
use_max_tag = true
exclude_regex = ".*(pre|a|alpha|b|beta|r|rc).*"

[wlr-randr]
source = "git"
git = "https://git.sr.ht/~emersion/wlr-randr"
prefix = "v"
use_max_tag = true
exclude_regex = ".*(pre|a|alpha|b|beta|r|rc).*"

# Other

[spotify]
source = "apt"
mirror = "http://repository.spotify.com/"
pkg = "spotify-client"
suite = "testing"
repo = "non-free"
exclude_regex = ".*(pre|a|alpha|b|beta|r|rc).*"
