---
# tasks file for add_package

# Stop the playbook if both the "package_debian" and the "package_arch" variables are empty or undefined
- name: Fail if the "package_debian" and the "package_arch" variables are empty or undefined
  ansible.builtin.fail:
    msg: The 'package_debian' and the 'package_arch' variables are both empty
  when: not package_debian and not package_arch

# Remove package(s) on Debian servers
- name: Remove package(s) - Debian
  ansible.builtin.apt:
    name: "{{ package_debian }}"
    state: absent
    autoremove: true
  when: ansible_facts['distribution'] == "Debian" and package_debian

# Remove package(s) on Arch servers
- name: Remove package(s) - Arch
  community.general.pacman:
    name: "{{ package_arch }}"
    state: absent
    extra_args: --recursive
  when: ansible_facts['distribution'] == "Archlinux" and package_arch
